import { test, expect } from "@playwright/test";
import { signIn } from "./helpers";

test("Requester creates a ticket; Staff claims, prioritizes, communicates and resolves it", async ({ page }) => {
  await signIn(page, "requester");
  await expect(page).toHaveURL(/\/my-tickets$/);
  await page.getByRole("navigation").getByRole("button", { name: "Create Ticket", exact: true }).click();
  await page.getByLabel("Category *", { exact: true }).selectOption({ label: "E2E Hardware" });
  await page.getByLabel("Related System *", { exact: true }).selectOption({ label: "E2E Laptop" });
  await page.getByLabel("Summary *", { exact: true }).fill("Real browser laptop repair");
  await page.getByLabel("Description *", { exact: true }).fill("Laptop battery fails during a lecture and needs inspection.");
  await page.getByRole("button", { name: "Submit Ticket", exact: true }).click();
  await page.getByRole("button", { name: "View Ticket Detail", exact: true }).click();
  await expect(page).toHaveURL(/\/tickets\/\d+$/);
  const ticketPath = new URL(page.url()).pathname;
  const ticketId = ticketPath.split("/").at(-1);
  const readTicket = async () => (await page.request.get(`http://localhost:3006/api${ticketPath}`)).json();
  let data = await readTicket();
  expect(data.itPriority).toBe(data.requestedPriority);
  expect(data.currentStatus).toBe("NEW");
  await page.getByRole("button", { name: "Logout", exact: true }).click();
  await signIn(page, "staff");
  await expect(page).toHaveURL(/\/staff\/tickets$/);
  await page.getByLabel("Search", { exact: true }).fill("Real browser laptop repair");
  await page.getByRole("button", { name: "Apply filters" }).click();
  await page.getByRole("button", { name: `Open ${data.ticketNumber}`, exact: true }).click();
  await page.getByRole("button", { name: "Claim Ticket", exact: true }).click();
  await expect(page.getByText("Ticket updated.", { exact: true })).toBeVisible();
  data = await readTicket();
  expect(data.owner.displayName).toBe("E2E staff");
  await page.getByLabel("Assigned owner").selectOption({ label: "E2E staff2 (IT Staff)" });
  await page.getByRole("button", { name: "Reassign owner", exact: true }).click();
  const reassigned = page.waitForResponse(r => r.url().endsWith(`/staff/tickets/${ticketId}/owner`) && r.request().method() === "PATCH");
  await page.getByRole("button", { name: "Confirm change" }).click();
  expect((await reassigned).status()).toBe(200);
  expect((await readTicket()).owner.displayName).toBe("E2E staff2");
  await page.getByLabel("Next status").selectOption("OPEN");
  await page.getByRole("button", { name: "Change status", exact: true }).click();
  const opened = page.waitForResponse(r => r.url().endsWith(`/staff/tickets/${ticketId}/status`) && r.request().method() === "POST");
  await page.getByRole("button", { name: "Confirm change" }).click();
  expect((await opened).status()).toBe(200);
  data = await readTicket();
  expect(data.currentStatus).toBe("OPEN");
  await page.getByLabel("Set IT Priority").selectOption("HIGH");
  const prioritySaved = page.waitForResponse(r => r.url().endsWith(`/staff/tickets/${ticketId}/priority`) && r.request().method() === "PATCH");
  await page.getByRole("button", { name: "Save IT Priority" }).click();
  expect((await prioritySaved).status()).toBe(200);
  expect((await readTicket()).itPriority).toBe("HIGH");
  await page.getByLabel("Public comment", { exact: true }).fill("The replacement battery is ready.");
  await page.getByRole("button", { name: "Post public comment" }).click();
  await expect(page.getByLabel("Public comment", { exact: true })).toHaveValue("");
  await page.getByLabel("Internal note", { exact: true }).fill("PRIVATE_REAL_E2E_NOTE");
  await page.getByRole("button", { name: "Post internal note" }).click();
  await expect(page.getByLabel("Internal note", { exact: true })).toHaveValue("");
  await page.getByRole("button", { name: "Logout", exact: true }).click();
  await signIn(page, "requester");
  await expect(page).toHaveURL(/\/my-tickets$/);
  await page.goto(ticketPath);
  await expect(page.getByText("The replacement battery is ready.", { exact: true })).toBeVisible();
  await expect(page.getByText("PRIVATE_REAL_E2E_NOTE")).toHaveCount(0);
  expect((await page.request.get(`http://localhost:3006/api/tickets/${ticketId}/notes`)).status()).toBe(403);
  await page.getByRole("button", { name: "Problem Appears Resolved", exact: true }).click();
  await page.getByRole("button", { name: "Confirm indication", exact: true }).click();
  await expect(page.getByText("Your resolution indication has been recorded.")).toBeVisible();
  expect((await readTicket()).currentStatus).toBe(data.currentStatus);
  await page.getByRole("button", { name: "Logout", exact: true }).click();
  await signIn(page, "staff");
  await expect(page).toHaveURL(/\/staff\/tickets$/);
  await page.goto(ticketPath);
  await page.getByLabel("Next status").selectOption("RESOLVED");
  await page.getByLabel("Public status reason (required)").fill("Replaced the battery and verified operation.");
  await page.getByRole("button", { name: "Change status", exact: true }).click();
  await page.getByRole("button", { name: "Confirm change" }).click();
  await expect(page.getByText("Ticket updated.", { exact: true })).toBeVisible();
  expect((await readTicket()).currentStatus).toBe("RESOLVED");
  for (const status of ["CLOSED", "REOPENED"]) {
    await page.getByLabel("Next status").selectOption(status);
    await page.getByLabel("Public status reason (required)").fill(status === "CLOSED" ? "Requester confirmed the repair is complete." : "The same battery problem has returned.");
    await page.getByRole("button", { name: "Change status", exact: true }).click();
    const changed = page.waitForResponse(r => r.url().endsWith(`/staff/tickets/${ticketId}/status`) && r.request().method() === "POST");
    await page.getByRole("button", { name: "Confirm change" }).click();
    expect((await changed).status()).toBe(200);
    expect((await readTicket()).currentStatus).toBe(status);
  }
  const reopened = await readTicket();
  expect(reopened.resolvedAt).toBeNull();
  expect(reopened.closedAt).toBeNull();
  expect(reopened.requesterResolutionIndicatedAt).toBeNull();
  await page.getByRole("button", { name: "Logout", exact: true }).click();
  await signIn(page, "admin");
  await expect(page).toHaveURL(/\/admin\/users$/);
  await page.goto(ticketPath);
  await expect(page.getByText("PRIVATE_REAL_E2E_NOTE", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Change status", exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Post internal note" })).toHaveCount(0);
});
